name: Test workflow

on: [pull_request, issue_comment]

env:
  APP_NAME: frontend-sme-dashboard
  # HOME: /actions-runner/_work
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
  PROJECT_NAME: onboarding
  ImageOS: ubuntu20

jobs:
  test-workflow-1:
    name: Test workflow 1
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: E2E Test Webhook
        run: echo "hello 1"

  test-workflow-2:
    name: Test workflow 2
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, format('https://sme-dashboard-pr-{0}.dev.razorpay.in', github.event.issue.number)) }}
    steps:
      - name: Checkout latest code of PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Fetch data of comment's associated PR
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: wait for Test workflow 1
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: ${{ steps.comment-branch.outputs.head_sha }}
          check-name: Test workflow 1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: E2E Test Webhook
        run: echo "hello"